import { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'

// ─── Data ─────────────────────────────────────────────────────────────────────

const slides = [
  {
    tag: '✦ Career & Success',
    title: 'Your Stars Know the Career Path You Were Born to Walk',
    desc: 'Stop guessing your next move. Get a detailed Career Report powered by Vedic Astrology — revealing your strengths, ideal profession, and the exact timing to act.',
    btn1: 'Get Career Report',   btn1Route: '/reports/career-report',
    btn2: 'Book a Consultation', btn2Route: '/consultation',
    image: '/slide1.png',
  },
  {
    tag: '✦ Meet Astro Aaditya Narayan',
    title: 'Thousands Have Transformed Their Lives. Your Turn Starts Here.',
    desc: 'With years of Vedic expertise and a heart for genuine guidance, Astro Aaditya Narayan has helped people across the world find clarity, purpose, and peace.',
    btn1: 'Book a Session', btn1Route: '/consultation',
    btn2: 'Learn More',     btn2Route: '/about',
    image: '/slide2.png',
  },
  {
    tag: '✦ Premium Kundli',
    title: 'Your Most Personal Document — Written in the Language of the Stars',
    desc: 'A premium hand-crafted Kundli with deep planetary analysis, life predictions, and Vedic remedies — built uniquely for you, not generated by software.',
    btn1: 'Get My Kundli', btn1Route: '/reports/premium-kundali',
    btn2: 'Know More',     btn2Route: '/reports',
    image: '/slide4.png',
  },
  {
    tag: '✦ Spiritual Guidance',
    title: 'Real Wisdom. Real Answers. One Trusted Guide by Your Side.',
    desc: "Whether it's love, career, health, or purpose — get honest, heart-centred guidance rooted in authentic Vedic tradition. No scripts. No shortcuts.",
    btn1: 'Start Your Journey', btn1Route: '/consultation',
    btn2: 'Book a Session',     btn2Route: '/consultation',
    image: '/slide5.png',
  },
  {
    tag: '✦ Wealth & Fortune',
    title: 'Unlock the Planetary Secrets Behind Your Wealth and Abundance',
    desc: "Find out which periods are financially powerful for you, what's blocking your growth, and the exact Vedic remedies to attract lasting prosperity.",
    btn1: 'Get Fortune Report',  btn1Route: '/reports/fortune-report',
    btn2: 'Book a Consultation', btn2Route: '/consultation',
    image: '/slide6.png',
  },
]

const TICKER = [
  'Divine Guidance for Life',
  'Personalized Astrology Consultation',
  'Couple Kundali Matching',
  'Career Report',
  'Vedic Astrology Course',
]

// ─── Typography tokens (mirrors Stats.tsx) ────────────────────────────────────
// Display serif  → Georgia (same as Stats numbers & section heading)
// Body / utility → "Segoe UI" stack (same as Stats labels / eyebrow)
// Scale uses clamp() throughout — fluid from 320 px to 1440 px

export default function Hero() {
  const [current, setCurrent] = useState(0)
  const [angle, setAngle]     = useState(0)
  const navigate              = useNavigate()

  // Auto-advance
  useEffect(() => {
    const t = setInterval(() => setCurrent(p => (p + 1) % slides.length), 4000)
    return () => clearInterval(t)
  }, [])

  // Slow chakra rotation
  useEffect(() => {
    const t = setInterval(() => setAngle(a => (a + 0.3) % 360), 16)
    return () => clearInterval(t)
  }, [])

  const slide = slides[current]

  return (
    <>
      <style>{CSS}</style>

      <section className="hero">
        {/* Navigation arrows */}
        <button className="hero-arrow hero-arrow--prev" aria-label="Previous slide"
          onClick={() => setCurrent(p => (p - 1 + slides.length) % slides.length)}>‹</button>
        <button className="hero-arrow hero-arrow--next" aria-label="Next slide"
          onClick={() => setCurrent(p => (p + 1) % slides.length)}>›</button>

        {/* ── LEFT: text ─────────────────────────────────────────────────────── */}
        <div key={`txt-${current}`} className="hero-left hero-fade">

          {/* Tag — mirrors "Vedic Astrology & Spiritual Guidance" badge:
              11px / letter-spacing 0.2em / uppercase / sans-serif              */}
          <span className="hero-tag">{slide.tag}</span>

          {/* Headline — Georgia, fluid clamp(24px → 48px), weight 800
              Same typeface & weight as Stats numbers and section heading        */}
          <h1 className="hero-title">{slide.title}</h1>

          {/* Body — sans-serif, fluid clamp(13px → 16px), matches Stats labels  */}
          <p className="hero-desc">{slide.desc}</p>

          <div className="hero-btns">
            {/* Primary — solid amber (matches Stats gold accent bar colour)     */}
            <button className="hero-btn hero-btn--primary"
              onClick={() => navigate(slide.btn1Route)}>
              {slide.btn1}
            </button>
            {/* Secondary — ghost white                                          */}
            <button className="hero-btn hero-btn--ghost"
              onClick={() => navigate(slide.btn2Route)}>
              {slide.btn2}
            </button>
          </div>
        </div>

        {/* ── RIGHT: chakra wheel + slide image ─────────────────────────────── */}
        <div className="hero-right">
          <img
            src="/chakra.png" alt=""
            className="hero-chakra"
            style={{ transform: `translate(-50%,-50%) rotate(${angle}deg)` }}
          />
          <div key={`img-${current}`} className="hero-img-wrap hero-fade">
            <img src={slide.image} alt={slide.tag} />
          </div>
        </div>

        {/* Slide dots */}
        <div className="hero-dots" role="tablist" aria-label="Slides">
          {slides.map((_, i) => (
            <button key={i} role="tab" aria-selected={i === current}
              className={`hero-dot${i === current ? ' hero-dot--active' : ''}`}
              onClick={() => setCurrent(i)} />
          ))}
        </div>
      </section>

      {/* ── Ticker ─────────────────────────────────────────────────────────── */}
      <div className="hero-ticker-wrap" aria-hidden>
        <div className="hero-ticker">
          {[...TICKER, ...TICKER].map((t, i) => (
            <span key={i} className="hero-ticker-item">
              {t}<span className="hero-ticker-star">✦</span>
            </span>
          ))}
        </div>
      </div>
    </>
  )
}

// ─── CSS ──────────────────────────────────────────────────────────────────────

const CSS = `
  /* ── Keyframes ───────────────────────────────────────────────────────────── */
  @keyframes hero-fadeSlide {
    from { opacity: 0; transform: translateY(16px); }
    to   { opacity: 1; transform: translateY(0); }
  }
  @keyframes hero-ticker {
    from { transform: translateX(0); }
    to   { transform: translateX(-50%); }
  }

  .hero-fade { animation: hero-fadeSlide 0.48s ease forwards; }

  /* ── Global reset guard ───────────────────────────────────────────────────
     body { font-family: Georgia } bleeds into buttons/inputs unless stopped.
     Scope the override to .hero so it doesn't affect other components.       */
  .hero button { font-family: "Segoe UI","Helvetica Neue",Arial,sans-serif; }

  /* ── Section shell ───────────────────────────────────────────────────────── */
  .hero {
    background: linear-gradient(135deg, #c47a1e 0%, #b8691a 100%);
    color: #fff;
    position: relative;
    overflow: hidden;
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: center;
    gap: clamp(24px, 4vw, 64px);
    padding: clamp(48px, 7vw, 110px) clamp(24px, 8%, 140px) clamp(64px, 8vw, 120px);
    /* was capped at 580px — now scales further on large/ultra-wide screens */
    min-height: clamp(420px, 46vw, 720px);
  }

  /* ── Left column ─────────────────────────────────────────────────────────── */
  .hero-left {
    flex: 1 1 0;
    min-width: 0;
    /* was max-width: 540px — too narrow on big screens, content looked tiny/lost in whitespace */
    max-width: 680px;
    z-index: 2;
  }

  /* Tag — exact same treatment as Stats eyebrow:
     font-size 11px / letter-spacing 0.2em / uppercase / Segoe UI stack        */
  .hero-tag {
    display: inline-block;
    font-family: "Segoe UI","Helvetica Neue",Arial,sans-serif;
    font-size: clamp(11px, 0.9vw, 13px);
    font-weight: 600;
    letter-spacing: 0.20em;
    text-transform: uppercase;
    border: 1px solid rgba(255,255,255,0.42);
    border-radius: 20px;
    padding: 5px 14px;
    margin-bottom: 18px;
    color: rgba(255,255,255,0.92);
    line-height: 1;
  }

  /* Headline — Georgia serif, clamp(24px → 60px), weight 800
     Raised the upper bound so it doesn't plateau on large desktops            */
  .hero-title {
    font-family: 'Playfair Display', Georgia, serif;
    font-size: clamp(24px, 3.6vw, 60px);
    font-weight: 800;
    line-height: 1.18;
    letter-spacing: -0.5px;
    margin: 0 0 clamp(12px, 2vw, 18px);
    color: #fff;
  }

  /* Body copy — same sans-serif stack as Stats labels; clamp(13px → 18px)     */
  .hero-desc {
    font-family: "Segoe UI","Helvetica Neue",Arial,sans-serif;
    font-size: clamp(13px, 1.2vw, 18px);
    line-height: 1.65;
    font-weight: 400;
    color: rgba(255,255,255,0.88);
    margin: 0 0 clamp(22px, 3vw, 32px);
    letter-spacing: 0.01em;
  }

  /* Button row */
  .hero-btns {
    display: flex;
    gap: 12px;
    flex-wrap: wrap;
  }

  /* Both buttons share the same base rhythm */
  .hero-btn {
    font-family: "Segoe UI","Helvetica Neue",Arial,sans-serif;
    font-size: clamp(13px, 1vw, 17px);
    font-weight: 700;
    letter-spacing: 0.03em;
    padding: clamp(10px,1.2vw,16px) clamp(20px,2.2vw,34px);
    border-radius: 30px;
    cursor: pointer;
    transition: opacity 0.2s ease, transform 0.2s ease;
    line-height: 1;
  }
  .hero-btn:hover { opacity: 0.88; transform: translateY(-2px); }

  /* Primary — amber fill with white border (matches Stats gold accent bar)     */
  .hero-btn--primary {
    background: #c47a1e;
    color: #fff;
    border: 2px solid #fff;
  }
  /* Ghost — transparent */
  .hero-btn--ghost {
    background: transparent;
    color: #fff;
    border: 2px solid rgba(255,255,255,0.50);
  }

  /* ── Right column ────────────────────────────────────────────────────────── */
  .hero-right {
    flex-shrink: 0;
    position: relative;
    /* was capped at 480px — now grows further on large screens */
    width: clamp(240px, 30vw, 600px);
    height: clamp(240px, 30vw, 600px);
    display: flex;
    align-items: center;
    justify-content: center;
    z-index: 2;
  }

  /* Chakra wheel */
  .hero-chakra {
    position: absolute;
    top: 50%; left: 50%;
    width: 100%; height: 100%;
    object-fit: contain;
    opacity: 0.42;
    pointer-events: none;
    z-index: 0;
  }

  /* Slide image */
  .hero-img-wrap {
    position: relative;
    z-index: 1;
    width: 55%; height: 80%;
    display: flex;
    align-items: center;
    justify-content: center;
  }
  .hero-img-wrap img {
    width: 100%; height: 100%;
    object-fit: contain;
    object-position: center;
    display: block;
  }

  /* ── Navigation arrows ───────────────────────────────────────────────────── */
  .hero-arrow {
    position: absolute;
    top: 50%;
    transform: translateY(-50%);
    background: rgba(255,255,255,0.15);
    border: 1px solid rgba(255,255,255,0.30);
    color: #fff;
    width: clamp(32px, 3vw, 44px);
    height: clamp(32px, 3vw, 44px);
    border-radius: 50%;
    cursor: pointer;
    font-size: clamp(18px, 2vw, 24px);
    z-index: 10;
    display: flex;
    align-items: center;
    justify-content: center;
    transition: background 0.2s ease;
    line-height: 1;
  }
  .hero-arrow:hover { background: rgba(255,255,255,0.28); }
  .hero-arrow--prev { left: clamp(8px, 1.5vw, 20px); }
  .hero-arrow--next { right: clamp(8px, 1.5vw, 20px); }

  /* ── Slide dots ──────────────────────────────────────────────────────────── */
  .hero-dots {
    position: absolute;
    bottom: clamp(14px, 2vw, 24px);
    left: 50%;
    transform: translateX(-50%);
    display: flex;
    gap: 7px;
    z-index: 10;
  }
  .hero-dot {
    height: 7px;
    width: 7px;
    border-radius: 4px;
    border: none;
    cursor: pointer;
    background: rgba(255,255,255,0.40);
    transition: width 0.3s ease, background 0.3s ease;
    padding: 0;
  }
  .hero-dot--active {
    width: 22px;
    background: #fff;
  }

  /* ── Ticker ──────────────────────────────────────────────────────────────── */
  .hero-ticker-wrap {
    background: #7a3e0a;
    padding: clamp(9px,1.2vw,13px) 0;
    overflow: hidden;
  }
  .hero-ticker {
    display: flex;
    gap: 64px;
    animation: hero-ticker 25s linear infinite;
    white-space: nowrap;
    /* Same sans-serif stack, same 11px uppercase treatment as hero tag         */
    font-family: "Segoe UI","Helvetica Neue",Arial,sans-serif;
    font-size: clamp(11px, 1.1vw, 13px);
    font-weight: 600;
    letter-spacing: 0.04em;
    color: #fff;
  }
  .hero-ticker-item {
    display: inline-flex;
    align-items: center;
    gap: 36px;
  }
  .hero-ticker-star {
    color: #f0c060;
    font-size: 9px;
  }

  /* ── Responsive ──────────────────────────────────────────────────────────── */

  /* Large desktop / ultra-wide — was missing, so everything plateaued past ~1440px */
  @media (min-width: 1440px) {
    .hero { padding-left: 100px; padding-right: 100px; }
  }

  /* Tablet */
  @media (max-width: 900px) and (min-width: 641px) {
    .hero { padding: 48px 32px 68px; }
    .hero-right { width: 280px; height: 280px; }
  }

  /* Mobile */
  @media (max-width: 640px) {
    .hero {
      flex-direction: column;
      align-items: center;
      text-align: center;
      padding: 36px 20px 60px;
      min-height: unset;
      gap: 20px;
    }
    .hero-left  { max-width: 100%; order: 2; }
    .hero-right { order: 1; width: clamp(180px,60vw,260px); height: clamp(180px,60vw,260px); flex-shrink: 0; }
    .hero-btns  { justify-content: center; }
    /* On mobile the headline drops slightly so the tag+title+desc still fit   */
    .hero-title { font-size: clamp(22px, 6vw, 32px); }
    .hero-arrow { width: 30px; height: 30px; font-size: 16px; }
  }

  /* Small mobile — extra safety */
  @media (max-width: 380px) {
    .hero-title { font-size: 21px; }
    .hero-desc  { font-size: 13px; }
  }
`
